PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS tasks (
  t_id INTEGER PRIMARY KEY AUTOINCREMENT,
  t_name TEXT NOT NULL,
  t_priority INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
  u_id INTEGER PRIMARY KEY AUTOINCREMENT,
  u_name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
  s_id INTEGER PRIMARY KEY AUTOINCREMENT,
  s_task INTEGER NOT NULL,
  s_user INTEGER NOT NULL,
  s_duration INTEGER NOT NULL,
  s_comment TEXT NOT NULL,
  FOREIGN KEY (s_task) REFERENCES tasks(t_id) ON DELETE CASCADE,
  FOREIGN KEY (s_user) REFERENCES users(u_id) ON DELETE CASCADE
);